# Ironically the task runner is itself a dev dependency of the project.
# To install it run the following command:
#
# go install github.com/go-task/task/v3/cmd/task@latest

version: '3'

tasks:
  fmt:
    cmds:
      - goimports -local github.com/davidmdm,github.com/davidmdm/yoke -w .
      - gofumpt -w .

  test:
    cmds:
      - kind delete cluster --name=tests && kind create cluster --name=tests
      - go test -coverprofile cover.out -p 1 -v ./...

  update-deps:
    cmds:
      - go get -u ./...
      - go get github.com/tetratelabs/wazero@v1.6.0
      - go mod tidy

  wasm:
    cmds:
      - task: kube
      - task: pg
      - task: redis

  yokecd-installer:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o yokecd-installer.wasm ./cmd/yokecd-installer

  kube:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o kube.wasm ./cmd/examples/kube

  pg:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o pg.wasm ./cmd/examples/pg

  redis:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o redis.wasm ./cmd/examples/redis
